/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:userControlWindow:564233:
  appc.background(230);
} //_CODE_:userControlWindow:564233:

public void wavelengthSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:wavelengthSlider:289796:
  //println("wavelengthSlider - GCustomSlider >> GEvent." + event + " @ " + millis());
  wavelength = wavelengthSlider.getValueI();
  redraw();
  //println("wavelength:" + wavelength);
} //_CODE_:wavelengthSlider:289796:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  userControlWindow = GWindow.getWindow(this, "Window title", 0, 0, 500, 500, JAVA2D);
  userControlWindow.noLoop();
  userControlWindow.setActionOnClose(G4P.KEEP_OPEN);
  userControlWindow.addDrawHandler(this, "win_draw1");
  wavelengthLabel = new GLabel(userControlWindow, 19, 33, 80, 20);
  wavelengthLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  wavelengthLabel.setText("Wavelength");
  wavelengthLabel.setOpaque(false);
  wavelengthSlider = new GCustomSlider(userControlWindow, 102, 24, 360, 63, "grey_blue");
  wavelengthSlider.setShowValue(true);
  wavelengthSlider.setLimits(560, 380, 740);
  wavelengthSlider.setNbrTicks(36);
  wavelengthSlider.setStickToTicks(true);
  wavelengthSlider.setShowTicks(true);
  wavelengthSlider.setNumberFormat(G4P.INTEGER, 0);
  wavelengthSlider.setOpaque(false);
  wavelengthSlider.addEventHandler(this, "wavelengthSliderChanged");
  userControlWindow.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow userControlWindow;
GLabel wavelengthLabel; 
GCustomSlider wavelengthSlider; 
